// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg3ns83toOua658I1luCNr7sz6MtB6dJM',
    appId: '1:766622784776:web:e972885857db8162ba60bd',
    messagingSenderId: '766622784776',
    projectId: 'insta-project-a5258',
    authDomain: 'insta-project-a5258.firebaseapp.com',
    storageBucket: 'insta-project-a5258.appspot.com',
    measurementId: 'G-B5H2QWM9FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPkM54waM7GXWNstpYmTHTRKRQYOXcR40',
    appId: '1:766622784776:android:dfffa3926294bc07ba60bd',
    messagingSenderId: '766622784776',
    projectId: 'insta-project-a5258',
    storageBucket: 'insta-project-a5258.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-yG09Q_rQj2QePFFHQAB4FLG91y5ajrU',
    appId: '1:766622784776:ios:37ae6c5793497847ba60bd',
    messagingSenderId: '766622784776',
    projectId: 'insta-project-a5258',
    storageBucket: 'insta-project-a5258.appspot.com',
    androidClientId: '766622784776-4q90tlsvh8gb64luo5124mrjrh0equda.apps.googleusercontent.com',
    iosClientId: '766622784776-fcu0afovj3d59fpq1tj80b77sst2areu.apps.googleusercontent.com',
    iosBundleId: 's',
  );
}
